### ISSUE TITLE
Unable to connect to MySQL 8

### ISSUE THREAD

**Issue by Reelix** [mgefvert/MyRawClient#1]
Hello!

You probably don't update this anymore seeing as how the last commit was 2 years ago, but I was looking for a light-weight MySQL Lib (This one is 1/13th the size of the main one) and came across yours.

It was working well until I hit a MySQL 8 (Specifically 8.0.19) Server.

After the handshake, an exception is thrown:

```ERR 1251: #08004 Client does not support authentication protocol requested by server; consider upgrading MySQL client```

Since it tests positive for an error packet over at

https://github.com/mgefvert/MyRawClient/blob/ec2c8bf52564596bcd9f736caaa52f252590a09f/MyRawClient/PacketHandlers/DefaultPacketHandler.cs#L34

Don't suppose you'd consider adding MySQL 8 Support to this lib? :)

**Comment by mgefvert** [comment]
I am surprised to see that someone is using this :) I built it a while ago because I was trying to write a mysqldump client, but the .NET library had such abysmal performance because of all the allocations internally. And now they've added SSH libs and everything else to the MySQL client.

I can't promise anything as I'm mostly working with SQL Server these days, but I might take a look at it and see if I can come up with something.

**Comment by Reelix** [comment]
No problem :) I was looking into coding something that interfaced with MySQL on a low-level due to the MASSIVE size of the default library and all its included references. I had the initial handshake partially parsed when I discovered yours. Your one is 54kb compiled in Release which is great :p

**Comment by mgefvert** [comment]
I looked into it over the weekend ... unfortunately, they don't seem to like making things easy for developers. I don't know if it's something I feel like implementing, which is unfortunate. But if you ever want to submit a pull request or a working sample, I'd be more than happy to implement it!
